version: "3.5"

services:
  inquiry_fe:
    build:
      context: ./
    image: "rsidevs/inquiry:01"
    deploy:
      replicas: 2
    restart: unless-stopped
    command: bash -c "node index.js"
    ports:
      - "4051:4051"
