version: "3.5"
services:
  app_dev:
    build:
      context: ./
    image: "rsidevs/inquiry"
    restart: unless-stopped
    command: bash -c "node index.js"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "4051:4051"
