version: "3.5"
services:
  app_dev:
    build:
      context: ./
    image: "inquiry_fe"
    container_name: inquiry_fe
    restart: unless-stopped
    command: bash -c "node index.js"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "4051:4051"
    stdin_open: true
    tty: true
