version: "3.5"

services:
  app_dev:
    build:
      context: ./
    image: "inquiry_fe"
    restart: unless-stopped
    command: bash -c "node index.js"
    ports:
      - "4051:4051"
# Version of Docker-compose
# version: "3.9"
# services:
#   # Add the node-js service
#   server:
#     # Location to the server dockerfile
#     build:
#       context:
#         ./server
#         # Name of the dockerfile
#       dockerfile: Dockerfile
#     # container_name: react-server
#     ports:
#       # Host port:Container port
#       - "4005:4005"
#     volumes:
#       # Bind-mounts configuration
#       - ./server:/app
#   client:
#     # Location to the client dockerfile
#     build:
#       context:
#         ./client
#         # Name of the dockerfile
#       dockerfile: Dockerfile
#     command: bash -c "node index.js"
#     ports:
#       # Host port:Container port
#       - "4051:4051"
#     stdin_open: true
