version: "3.5"

services:
  app:
    build:
      context: ./
    image: "inquiry_app"
    container_name: inquiry_app
    restart: unless-stopped
    command: bash -c "node index.js"
    ports:
      - "4051:4051"
