version: "3.5"
services:
        app:
                build:
                        context: ./
                image: "helpdesk_fe"
                container_name: "helpdesk_fe"
                restart: unless-stopped
                command: bash -c "node index.js"
                ports:
                        - "8051:8051"