resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: GitLab # <-- replace with your integration
      path: rsi-development-team/elany/aeros-frontend/inquiry # <-- replace with your repository name
      branches:
        include: jwh-jFrog

  - name: dbp_image
    type: Image
    configuration:
      registry: art # <-- replace with your artifactory integration
      sourceRepository: docker-local # <-- required if registry is Artifactory
      imageName: elanyrsi.jfrog.io/docker-local/dbp # < -- replace with your image path and name
      imageTag: latest
      autoPull: true

  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1

  - name: cron_trigger_docker
    type: CronTrigger
    configuration:
      interval: "0 2 * * *"

pipelines:
  - name: Inquiry_Test
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: elanyrsi.jfrog.io/docker-local/dbp # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
            - name: cron_trigger_docker
          integrations:
            - name: art # <-- replace with your artifactory integration
        execution:
          onStart:
            # - msg="Run description updated from step $step_id"
            # - update_run_description "$msg"
            - update_run_description "Add custom text for every run. Example - Build and push Docker image to Artifactory."
          # onExecute:
          # - docker build -t my-node-server .
          # - cd ./dependencyState/resources/dbp_repo
          # - ls
          # - sudo docker-compose -f docker-compose-jfrog.yml build
          # - sudo docker-compose -f docker-compose-jfrog.yml up -d

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-dev
          integrations:
            - name: art # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: docker_compose
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputSteps:
            - name: docker_push
          inputResources:
            - name: dbp_repo
          outputResources:
            - name: dbp_build_info
        execution:
          onStart:
            - echo "Executing Docker Compose..."
          onExecute:
            - docker build -t my-node-server .
      - cd ./dependencyState/resources/dbp_repo
      - ls
      - sudo docker-compose -f docker-compose-jfrog.yml build
      - sudo docker-compose -d -f docker-compose-jfrog.yml up

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-dev
          integrations:
            - name: art
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
