---
name: RSI Automated Build

on:
  push:
    branches:
      - jwh-github-actions
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # Enable multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # setup caching and use new Buildx Docker CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      # add Docker meta data for dynamic tagging
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: rsidevs/inquiry
          flavor: |
            latest=true
          tags: |

            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      # build and push image
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
